### ISSUE TITLE
Fix authentication across pages

### ISSUE THREAD

**Issue by akhilojha** [requestly/library#8]

**Comment by sachinjain024** [comment]
@akhilojha What do you mean by fixing authentication across pages ? Which pages you are talking about ? 

All requestly pages have already been moved to single domain requestly.in. For example:
Rules Page - requestly.in/rules
Content/Blog - requestly.in/content
Home Site - requestly.in

And Library should be requestly.in/library

So if a user is authenticated on one of the screens, he should be authenticated across entire requestly ecosystem.

**Comment by akhilojha** [comment]
@sachinjain024 - i meant only for library service - make sure google library can be loaded and if not then redirect to login page.  Its done now.
User if once logged in via google should be able to access entire requestly. No need for separate login for library service.
